command: ["uv", "run", "start-app"]
env:
  - name: MLFLOW_TRACKING_URI
    value: "databricks"
  - name: LAKEBASE_AUTOSCALING_ENDPOINT
    valueFrom: postgres
  - name: VS_INDEX_NAME
    value: "pro_bronze.labs.mauro_bot_vs_index"
  - name: LLM_ENDPOINT
    value: "mauro-bot-llm-endpoint"
  - name: USE_AI_GATEWAY
    value: "true"
